// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Genre struct {
	ID        int32
	Genre     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Movie struct {
	ID          int32
	Title       sql.NullString
	ReleaseDate sql.NullTime
	Runtime     sql.NullInt32
	MpaaRating  sql.NullString
	Description sql.NullString
	Image       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type MoviesGenre struct {
	ID        int32
	MovieID   int32
	GenreID   int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int32
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
